package com.boxsender.reports;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Report Repository Interface
 *
 * This interface provides data access operations for the Report entity.
 * Extends JpaRepository to inherit standard CRUD operations automatically.
 *
 * Custom methods for finding reports by type and employee.
 */
public interface ReportRepository extends JpaRepository<Report, Long> {

    /**
     * Finds all reports of a specific type
     *
     * @param reportType the type of report (e.g., "DAILY", "OVERDUE")
     * @return List of reports of that type
     */
    List<Report> findByReportType(String reportType);

    /**
     * Finds all reports generated by a specific employee
     *
     * @param employeeId the ID of the employee
     * @return List of reports generated by that employee
     */
    List<Report> findByGeneratedById(Long employeeId);

    /**
     * Finds all reports ordered by generation date (newest first)
     *
     * @return List of all reports ordered by date descending
     */
    List<Report> findAllByOrderByGeneratedDateDesc();
}
